import AppAuth
import AuthenticationServices
import Combine
import Foundation
import UIKit

// MARK: - Client

@MainActor
public class ScalekitClient: NSObject, ObservableObject {
    /// The normalized environment host (scheme and trailing slashes stripped).
    public let environmentURL: String
    public let clientId: String

    private let redirectURI: URL
    private let tokenStore: KeychainTokenStore

    /// In-flight login flow — prevents concurrent login attempts.
    private var currentAuthFlow: OIDExternalUserAgentSession?
    private var isLoginInProgress = false

    private var cachedConfig: OIDServiceConfiguration?
    private var configFetchedAt: Date?

    /// In-flight refresh task — concurrent renew() calls share this task
    /// instead of each triggering a separate token exchange.
    /// Critical for Scalekit's rotating refresh tokens: a second concurrent
    /// exchange would fail because the first already consumed the token.
    private var refreshTask: Task<Void, Error>?

    @Published public var credentials: ScalekitCredentials?

    public var isAuthenticated: Bool { credentials != nil }

    public init(environmentURL: String, clientId: String, redirectScheme: String) {
        self.environmentURL = Self.extractHost(environmentURL)
        self.clientId = clientId
        guard let uri = URL(string: "\(redirectScheme):/oauth2redirect") else {
            fatalError("[ScalekitAuth] Invalid redirectScheme: '\(redirectScheme)'")
        }
        self.redirectURI = uri
        self.tokenStore = KeychainTokenStore(service: "com.scalekit.\(self.environmentURL)")
        let loaded = tokenStore.load()
        self.credentials = loaded
        super.init()
        loaded?.authState.stateChangeDelegate = self
        loaded?.authState.errorDelegate = self
    }

    /// Accepts "https://env.scalekit.cloud", "env.scalekit.cloud", or
    /// "https://env.scalekit.cloud/" and returns the bare host in all cases.
    private static func extractHost(_ raw: String) -> String {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.contains("://"),
           let url = URL(string: trimmed),
           let host = url.host {
            return host
        }
        return trimmed.components(separatedBy: "/").first ?? trimmed
    }

    // MARK: - Login

    public func login(options: AuthorizationOptions? = nil) async throws {
        guard !isLoginInProgress else { throw ScalekitError.loginInProgress }
        isLoginInProgress = true
        defer { isLoginInProgress = false }

        let config = try await discoverConfig()
        let extra = (options ?? AuthorizationOptions()).asAdditionalParameters

        let request = OIDAuthorizationRequest(
            configuration: config,
            clientId: clientId,
            scopes: [OIDScopeOpenID, OIDScopeProfile, OIDScopeEmail, "offline_access"],
            redirectURL: redirectURI,
            responseType: OIDResponseTypeCode,
            additionalParameters: extra.isEmpty ? nil : extra
        )

        let vc = try topViewController()
        let authState: OIDAuthState = try await withCheckedThrowingContinuation { continuation in
            let flow = OIDAuthState.authState(byPresenting: request, presenting: vc) { [weak self] state, error in
                self?.currentAuthFlow = nil
                if let state {
                    continuation.resume(returning: state)
                } else if let error = error as NSError?,
                          error.code == OIDErrorCode.userCanceledAuthorizationFlow.rawValue {
                    continuation.resume(throwing: ScalekitError.cancelled)
                } else {
                    continuation.resume(throwing: error ?? ScalekitError.authFailed)
                }
            }
            self.currentAuthFlow = flow
        }

        let idToken = authState.lastTokenResponse?.idToken ?? authState.lastAuthorizationResponse.idToken

        if let idToken, let jwksURL = config.discoveryDocument?.jwksURL {
            do {
                try await JWTVerifier.verify(token: idToken, jwksURL: jwksURL)
            } catch {
                throw ScalekitError.tokenVerificationFailed(underlying: error)
            }
        }

        // Validate nonce using the nonce AppAuth actually sent (auto-generated by the request)
        let sentNonce = authState.lastAuthorizationResponse.request.nonce
        if let sentNonce, let idToken,
           let tokenNonce = JWT.claim("nonce", from: idToken) {
            guard tokenNonce == sentNonce else { throw ScalekitError.invalidIDToken }
        }

        let creds = ScalekitCredentials(authState: authState)
        authState.stateChangeDelegate = self
        authState.errorDelegate = self
        tokenStore.save(creds)
        credentials = creds
    }

    // MARK: - Logout

    public func logout() async {
        refreshTask?.cancel()
        refreshTask = nil
        defer {
            tokenStore.clear()
            credentials = nil
        }
        await fireEndSession()
    }

    // MARK: - Renew

    /// Refreshes the access token if expired.
    /// Concurrent calls are coalesced — all callers await the same in-flight
    /// refresh instead of each triggering a separate token exchange.
    public func renew() async throws {
        if let existing = refreshTask {
            return try await existing.value
        }

        let task = Task<Void, Error> {
            guard let creds = self.credentials else {
                throw ScalekitError.notAuthenticated
            }
            guard creds.authState.refreshToken != nil else {
                throw ScalekitError.noRefreshToken
            }

            try await withCheckedThrowingContinuation { (cont: CheckedContinuation<Void, Error>) in
                creds.authState.performAction { _, _, error in
                    if let error {
                        let nsError = error as NSError
                        if nsError.domain == OIDOAuthTokenErrorDomain {
                            cont.resume(throwing: ScalekitError.sessionRevoked)
                        } else if nsError.domain == NSURLErrorDomain {
                            cont.resume(throwing: ScalekitError.networkFailure(underlying: error))
                        } else {
                            cont.resume(throwing: ScalekitError.renewFailed(underlying: error))
                        }
                    } else {
                        cont.resume()
                    }
                }
            }
            // Save after continuation resumes — back on MainActor, no data race
            self.tokenStore.save(creds)
        }

        refreshTask = task
        defer { refreshTask = nil }
        try await task.value
    }

    // MARK: - Token claims

    /// Verifies the JWT signature and returns its decoded claims.
    /// Works for both access tokens and ID tokens — use this to extract
    /// custom claims your backend embeds in the access token.
    public func decodedClaims(from token: String) async throws -> [String: Any] {
        let config = try await discoverConfig()
        guard let jwksURL = config.discoveryDocument?.jwksURL else {
            throw ScalekitError.discoveryFailed
        }
        do {
            try await JWTVerifier.verify(token: token, jwksURL: jwksURL)
        } catch {
            throw ScalekitError.tokenVerificationFailed(underlying: error)
        }
        guard let claims = JWT.decode(token) else {
            throw ScalekitError.authFailed
        }
        return claims
    }

    // MARK: - Private

    private func discoverConfig() async throws -> OIDServiceConfiguration {
        if let config = cachedConfig,
           let fetchedAt = configFetchedAt,
           Date.now.timeIntervalSince(fetchedAt) < 3600 {
            return config
        }
        guard let issuer = URL(string: "https://\(environmentURL)") else {
            fatalError("[ScalekitAuth] Invalid environmentURL: '\(environmentURL)'")
        }
        let config = try await withCheckedThrowingContinuation { continuation in
            OIDAuthorizationService.discoverConfiguration(forIssuer: issuer) { config, error in
                if let config {
                    continuation.resume(returning: config)
                } else {
                    continuation.resume(throwing: error ?? ScalekitError.discoveryFailed)
                }
            }
        }
        cachedConfig = config
        configFetchedAt = .now
        return config
    }

    private func fireEndSession() async {
        guard let idToken = credentials?.idToken,
              let scheme = redirectURI.scheme else { return }

        let endpoint = credentials?.authState
            .lastAuthorizationResponse.request.configuration
            .discoveryDocument?.endSessionEndpoint
            ?? URL(string: "https://\(environmentURL)/oidc/logout")

        guard let endpoint,
              var components = URLComponents(url: endpoint, resolvingAgainstBaseURL: true) else { return }

        components.queryItems = [
            URLQueryItem(name: "id_token_hint", value: idToken),
            URLQueryItem(name: "post_logout_redirect_uri", value: "\(scheme)://logout")
        ]
        guard let url = components.url else { return }

        _ = try? await withCheckedThrowingContinuation { (cont: CheckedContinuation<URL?, Error>) in
            let session = ASWebAuthenticationSession(
                url: url,
                callbackURLScheme: redirectURI.scheme
            ) { callbackURL, _ in
                cont.resume(returning: callbackURL)
            }
            session.prefersEphemeralWebBrowserSession = false
            session.presentationContextProvider = self.presentationContext
            session.start()
            self.logoutSession = session
        }
        logoutSession = nil
    }

    private var logoutSession: ASWebAuthenticationSession?
    private let presentationContext = PresentationContext()

    private func topViewController() throws -> UIViewController {
        guard let scene = UIApplication.shared.connectedScenes
                  .first(where: { $0.activationState == .foregroundActive }) as? UIWindowScene,
              let root = scene.keyWindow?.rootViewController
        else { throw ScalekitError.authFailed }
        var top = root
        while let presented = top.presentedViewController { top = presented }
        return top
    }
}

// MARK: - AppAuth Delegates

extension ScalekitClient: OIDAuthStateChangeDelegate {
    public nonisolated func didChange(_ state: OIDAuthState) {
        Task { @MainActor in
            let creds = ScalekitCredentials(authState: state)
            self.tokenStore.save(creds)
            self.credentials = creds
        }
    }
}

extension ScalekitClient: OIDAuthStateErrorDelegate {
    public nonisolated func authState(_ state: OIDAuthState, didEncounterAuthorizationError error: Error) {
        Task { @MainActor in
            await self.logout()
        }
    }
}

private class PresentationContext: NSObject, ASWebAuthenticationPresentationContextProviding {
    func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
        let scenes = UIApplication.shared.connectedScenes.compactMap { $0 as? UIWindowScene }
        if let window = scenes.first(where: { $0.activationState == .foregroundActive })?.keyWindow {
            return window
        }
        if let window = scenes.flatMap(\.windows).first(where: \.isKeyWindow) {
            return window
        }
        if let scene = scenes.first {
            return UIWindow(windowScene: scene)
        }
        // Unreachable on iOS 13+ — every app has at least one UIWindowScene
        fatalError("[ScalekitAuth] No UIWindowScene available")
    }
}
